# Get list of entrants

In [1]:
import json
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

In [2]:
import os

auth_token = os.environ['SMASHGG_TOKEN']
api_version = 'alpha'

In [3]:
transport = RequestsHTTPTransport(
    url=f'https://api.start.gg/gql/{api_version}',
    headers={'Authorization': f'Bearer {auth_token}'},
    use_json=True,
)

client = Client(transport=transport, fetch_schema_from_transport=False)

In [4]:
# Define the API endpoint and query for tournament details
tournament_slug = "ngpr"
query = gql("""
query TournamentQuery($slug: String!) {
    tournament(slug: $slug) {
        id
        name
        city
        state
        countryCode
        startAt
        endAt
        events {
            id
            name
            numEntrants
        }
    }
}
""")

variables = {"slug": tournament_slug}

# Execute the query
try:
        tournament_result = client.execute(query, variable_values=variables)
        print(json.dumps(tournament_result, indent=2))
except Exception as e:
        print("Error fetching tournament details:", e)

{
  "tournament": {
    "id": 808121,
    "name": "New Game Plus Revival 8.13",
    "city": "Boston",
    "state": 3,
    "countryCode": "US",
    "startAt": 1752616800,
    "endAt": 1752638340,
    "events": [
      {
        "id": 1417057,
        "name": "Project+ Singles (Free!)",
        "numEntrants": 1
      },
      {
        "id": 1417055,
        "name": "Melee Singles",
        "numEntrants": 30
      },
      {
        "id": 1417056,
        "name": "Melee Redemption",
        "numEntrants": 9
      }
    ]
  }
}

In [5]:
# Extract the event id for "Melee Singles"
events = tournament_result['tournament']['events']
melee_singles_id = next((event['id'] for event in events if event['name'] == "Melee Singles"), None)
print("Melee Singles Event ID:", melee_singles_id)

Melee Singles Event ID: 1417055

In [6]:
# Query to get entrants for Melee Singles
entrants_query = gql("""
query EventEntrants($eventId: ID!) {
    event(id: $eventId) {
        entrants(query: {page: 1, perPage: 512}) {
            nodes {
                id
                name
                participants {
                    gamerTag
                }
            }
        }
    }
}
""")

entrants_variables = {"eventId": melee_singles_id}

try:
        entrants_result = client.execute(entrants_query, variable_values=entrants_variables)
        print(json.dumps(entrants_result, indent=2))
except Exception as e:
        print("Error fetching entrants:", e)

{
  "event": {
    "entrants": {
      "nodes": [
        {
          "id": 20701899,
          "name": "hc | pluto",
          "participants": [
            {
              "gamerTag": "pluto"
            }
          ]
        },
        {
          "id": 20701804,
          "name": "MAIF",
          "participants": [
            {
              "gamerTag": "MAIF"
            }
          ]
        },
        {
          "id": 20701789,
          "name": "hc | kraft",
          "participants": [
            {
              "gamerTag": "kraft"
            }
          ]
        },
        {
          "id": 20701782,
          "name": "BonkCushy",
          "participants": [
            {
              "gamerTag": "BonkCushy"
            }
          ]
        },
        {
          "id": 20700995,
          "name": "ThunderPaste",
          "participants": [
            {
              "gamerTag": "ThunderPaste"
            }
          ]
        },
        {
          "id": 20700993,
          "name": "hc | Pizza",
          "participants": [
            {
              "gamerTag": "Pizza"
            }
          ]
        },
        {
          "id": 20700969,
          "name": "hc | Jeep God",
          "participants": [
            {
              "gamerTag": "Jeep God"
            }
          ]
        },
        {
          "id": 20700952,
          "name": "Nico",
          "participants": [
            {
              "gamerTag": "Nico"
            }
          ]
        },
        {
          "id": 20700936,
          "name": "brennan",
          "participants": [
            {
              "gamerTag": "brennan"
            }
          ]
        },
        {
          "id": 20700640,
          "name": "Ares",
          "participants": [
            {
              "gamerTag": "Ares"
            }
          ]
        },
        {
          "id": 20700412,
          "name": "Sleeper",
          "participants": [
            {
              "gamerTag": "Sleeper"
            }
          ]
        },
        {
          "id": 20700362,
          "name": "regEx",
          "participants": [
            {
              "gamerTag": "regEx"
            }
          ]
        },
        {
          "id": 20700136,
          "name": "Zeeb | Skynative",
          "participants": [
            {
              "gamerTag": "Skynative"
            }
          ]
        },
        {
          "id": 20699963,
          "name": "nilo",
          "participants": [
            {
              "gamerTag": "nilo"
            }
          ]
        },
        {
          "id": 20699715,
          "name": "Karils | Conflict",
          "participants": [
            {
              "gamerTag": "Conflict"
            }
          ]
        },
        {
          "id": 20699209,
          "name": "Swartzy",
          "participants": [
            {
              "gamerTag": "Swartzy"
            }
          ]
        },
        {
          "id": 20699153,
          "name": "Qwerty",
          "participants": [
            {
              "gamerTag": "Qwerty"
            }
          ]
        },
        {
          "id": 20698616,
          "name": "hc | keke",
          "participants": [
            {
              "gamerTag": "keke"
            }
          ]
        },
        {
          "id": 20698528,
          "name": "hc | saucymain",
          "participants": [
            {
              "gamerTag": "saucymain"
            }
          ]
        },
        {
          "id": 20698084,
          "name": "hc | Babs",
          "participants": [
            {
              "gamerTag": "Babs"
            }
          ]
        },
        {
          "id": 20696744,
          "name": "Sweat",
          "participants": [
            {
              "gamerTag": "Sweat"
            }
          ]
        },
        {
          "id": 20695615,
          "name": "Nuggetz",
          "participants": [
            {
              "gamerTag": "Nuggetz"
            }
          ]
        },
        {
          "id": 20694180,
          "name": "Smyles",
          "participants": [
            {
              "gamerTag": "Smyles"
            }
          ]
        },
        {
          "id": 20691702,
          "name": "Exarch",
          "participants": [
            {
              "gamerTag": "Exarch"
            }
          ]
        },
        {
          "id": 20688969,
          "name": "yungsos",
          "participants": [
            {
              "gamerTag": "yungsos"
            }
          ]
        },
        {
          "id": 20687727,
          "name": "AUNTIE WOW | bleop",
          "participants": [
            {
              "gamerTag": "bleop"
            }
          ]
        },
        {
          "id": 20687556,
          "name": "Ant",
          "participants": [
            {
              "gamerTag": "Ant"
            }
          ]
        },
        {
          "id": 20686872,
          "name": "bfu",
          "participants": [
            {
              "gamerTag": "bfu"
            }
          ]
        },
        {
          "id": 20686853,
          "name": "\u30ac\u30c3\u30c4",
          "participants": [
            {
              "gamerTag": "\u30ac\u30c3\u30c4"
            }
          ]
        },
        {
          "id": 20668097,
          "name": "zaubermaus",
          "participants": [
            {
              "gamerTag": "zaubermaus"
            }
          ]
        }
      ]
    }
  }
}

In [13]:
import polars as pl

# Extract entrant data and flatten participants' gamerTags

entrant_nodes = entrants_result['event']['entrants']['nodes']
data = []
for entrant in entrant_nodes:
    entrant_id = entrant['id']
    entrant_name = entrant['name']
    # There may be multiple participants per entrant; join their gamerTags with comma
    gamer_tags = [p['gamerTag'] for p in entrant.get('participants', [])]
    gamer_tag = ', '.join(gamer_tags)
    data.append({'id': entrant_id, 'name': entrant_name, 'gamertag': gamer_tag})

entrants = pl.DataFrame(data)
entrants

shape: (30, 3)
┌──────────┬────────────────────┬──────────────┐
│ id       ┆ name               ┆ gamertag     │
│ ---      ┆ ---                ┆ ---          │
│ i64      ┆ str                ┆ str          │
╞══════════╪════════════════════╪══════════════╡
│ 20701899 ┆ hc | pluto         ┆ pluto        │
│ 20701804 ┆ MAIF               ┆ MAIF         │
│ 20701789 ┆ hc | kraft         ┆ kraft        │
│ 20701782 ┆ BonkCushy          ┆ BonkCushy    │
│ 20700995 ┆ ThunderPaste       ┆ ThunderPaste │
│ …        ┆ …                  ┆ …            │
│ 20687727 ┆ AUNTIE WOW | bleop ┆ bleop        │
│ 20687556 ┆ Ant                ┆ Ant          │
│ 20686872 ┆ bfu                ┆ bfu          │
│ 20686853 ┆ ガッツ             ┆ ガッツ       │
│ 20668097 ┆ zaubermaus         ┆ zaubermaus   │
└──────────┴────────────────────┴──────────────┘

In [19]:
entrant_gamertags = entrants.select(pl.col('gamertag').str.to_lowercase()).to_series().to_list()

# collect seeding

In [84]:
player_ratings = pl.read_parquet('data/player-ratings.parquet')

In [87]:
pl.Config(tbl_rows=100)
entrant_ratings = (
    entrants
    .with_columns(pl.col('gamertag').str.to_lowercase())
    .join(
        player_ratings
            .with_columns(pl.col('tag').str.split(' | ').list.last().str.to_lowercase()),
        how='full',
        left_on='gamertag',
        right_on='tag',
    )
    #.filter(
    #    (pl.col('tag').str.to_lowercase() == pl.col('gamertag').str.to_lowercase()) |
    #    pl.col('gamertag').is_null()
    #)
    .filter(pl.col('gamertag').is_not_null())
    .sort('rating', descending=True)
    .group_by('id').first()
    .sort('rating', descending=True)
)
display(entrant_ratings)

shape: (30, 6)
┌──────────┬────────────────────┬──────────────┬────────────────────────┬───────────┬──────────────┐
│ id       ┆ name               ┆ gamertag     ┆ url                    ┆ rating    ┆ tag          │
│ ---      ┆ ---                ┆ ---          ┆ ---                    ┆ ---       ┆ ---          │
│ i64      ┆ str                ┆ str          ┆ str                    ┆ f64       ┆ str          │
╞══════════╪════════════════════╪══════════════╪════════════════════════╪═══════════╪══════════════╡
│ 20700362 ┆ regEx              ┆ regex        ┆ /league/nemelee/player ┆ 36.887306 ┆ regex        │
│          ┆                    ┆              ┆ /1D8B9E3…              ┆           ┆              │
│ 20687556 ┆ Ant                ┆ ant          ┆ /league/nemelee/player ┆ 35.158962 ┆ ant          │
│          ┆                    ┆              ┆ /5DBCC34…              ┆           ┆              │
│ 20699715 ┆ Karils | Conflict  ┆ conflict     ┆ /league/nemelee/player ┆ 34.01907  ┆ conflict     │
│          ┆                    ┆              ┆ /38A911E…              ┆           ┆              │
│ 20698528 ┆ hc | saucymain     ┆ saucymain    ┆ /league/nemelee/player ┆ 33.159399 ┆ saucymain    │
│          ┆                    ┆              ┆ /2407F41…              ┆           ┆              │
│ 20696744 ┆ Sweat              ┆ sweat        ┆ /league/nemelee/player ┆ 33.128794 ┆ sweat        │
│          ┆                    ┆              ┆ /DF3CE0B…              ┆           ┆              │
│ 20701789 ┆ hc | kraft         ┆ kraft        ┆ /league/nemelee/player ┆ 31.636772 ┆ kraft        │
│          ┆                    ┆              ┆ /0CDB11B…              ┆           ┆              │
│ 20701782 ┆ BonkCushy          ┆ bonkcushy    ┆ /league/nemelee/player ┆ 30.556306 ┆ bonkcushy    │
│          ┆                    ┆              ┆ /1056255…              ┆           ┆              │
│ 20700995 ┆ ThunderPaste       ┆ thunderpaste ┆ /league/nemelee/player ┆ 30.168946 ┆ thunderpaste │
│          ┆                    ┆              ┆ /E545213…              ┆           ┆              │
│ 20699209 ┆ Swartzy            ┆ swartzy      ┆ /league/nemelee/player ┆ 29.017643 ┆ swartzy      │
│          ┆                    ┆              ┆ /2D23DC1…              ┆           ┆              │
│ 20700952 ┆ Nico               ┆ nico         ┆ /league/nemelee/player ┆ 28.755552 ┆ nico         │
│          ┆                    ┆              ┆ /D4FE06C…              ┆           ┆              │
│ 20668097 ┆ zaubermaus         ┆ zaubermaus   ┆ /league/nemelee/player ┆ 28.482155 ┆ zaubermaus   │
│          ┆                    ┆              ┆ /66DEE19…              ┆           ┆              │
│ 20698616 ┆ hc | keke          ┆ keke         ┆ /league/nemelee/player ┆ 28.156481 ┆ keke         │
│          ┆                    ┆              ┆ /ACFD51E…              ┆           ┆              │
│ 20700993 ┆ hc | Pizza         ┆ pizza        ┆ /league/nemelee/player ┆ 27.723123 ┆ pizza        │
│          ┆                    ┆              ┆ /73AF50A…              ┆           ┆              │
│ 20698084 ┆ hc | Babs          ┆ babs         ┆ /league/nemelee/player ┆ 27.089984 ┆ babs         │
│          ┆                    ┆              ┆ /03D1DA3…              ┆           ┆              │
│ 20700969 ┆ hc | Jeep God      ┆ jeep god     ┆ /league/nemelee/player ┆ 26.568589 ┆ jeep god     │
│          ┆                    ┆              ┆ /4990C91…              ┆           ┆              │
│ 20700412 ┆ Sleeper            ┆ sleeper      ┆ /league/nemelee/player ┆ 26.34154  ┆ sleeper      │
│          ┆                    ┆              ┆ /44E0B0C…              ┆           ┆              │
│ 20701899 ┆ hc | pluto         ┆ pluto        ┆ /league/nemelee/player ┆ 24.500493 ┆ pluto        │
│          ┆                    ┆              ┆ /25B1368…              ┆           ┆              │
│ 20687727 ┆ AUNTIE WOW | bleop ┆ bleop        ┆ /league/nemelee/player ┆ 24.471878 ┆ bleop        │
│          ┆                    ┆              ┆ /9DABAEA…              ┆           ┆              │
│ 20699153 ┆ Qwerty             ┆ qwerty       ┆ /league/nemelee/player ┆ 24.260187 ┆ qwerty       │
│          ┆                    ┆              ┆ /19B79D7…              ┆           ┆              │
│ 20686853 ┆ ガッツ             ┆ ガッツ       ┆ /league/nemelee/player ┆ 24.055288 ┆ ガッツ       │
│          ┆                    ┆              ┆ /806202F…              ┆           ┆              │
│ 20688969 ┆ yungsos            ┆ yungsos      ┆ /league/nemelee/player ┆ 22.378734 ┆ yungsos      │
│          ┆                    ┆              ┆ /BC547FD…              ┆           ┆              │
│ 20695615 ┆ Nuggetz            ┆ nuggetz      ┆ /league/nemelee/player ┆ 21.046891 ┆ nuggetz      │
│          ┆                    ┆              ┆ /DCB5FA5…              ┆           ┆              │
│ 20694180 ┆ Smyles             ┆ smyles       ┆ /league/nemelee/player ┆ 19.653269 ┆ smyles       │
│          ┆                    ┆              ┆ /24A071F…              ┆           ┆              │
│ 20700136 ┆ Zeeb | Skynative   ┆ skynative    ┆ /league/nemelee/player ┆ 19.101262 ┆ skynative    │
│          ┆                    ┆              ┆ /34F14CA…              ┆           ┆              │
│ 20686872 ┆ bfu                ┆ bfu          ┆ /league/nemelee/player ┆ 18.443477 ┆ bfu          │
│          ┆                    ┆              ┆ /E8A5E25…              ┆           ┆              │
│ 20699963 ┆ nilo               ┆ nilo         ┆ /league/nemelee/player ┆ 17.311287 ┆ nilo         │
│          ┆                    ┆              ┆ /860A914…              ┆           ┆              │
│ 20700640 ┆ Ares               ┆ ares         ┆ /league/nemelee/player ┆ 12.678184 ┆ ares         │
│          ┆                    ┆              ┆ /0448BEF…              ┆           ┆              │
│ 20701804 ┆ MAIF               ┆ maif         ┆ /league/nemelee/player ┆ 9.932394  ┆ maif         │
│          ┆                    ┆              ┆ /36266FF…              ┆           ┆              │
│ 20691702 ┆ Exarch             ┆ exarch       ┆ /league/nemelee/player ┆ 9.850652  ┆ exarch       │
│          ┆                    ┆              ┆ /BD62470…              ┆           ┆              │
│ 20700936 ┆ brennan            ┆ brennan      ┆ /league/nemelee/player ┆ 9.201359  ┆ brennan      │
│          ┆                    ┆              ┆ /5F2DF4E…              ┆           ┆              │
└──────────┴────────────────────┴──────────────┴────────────────────────┴───────────┴──────────────┘

In [ ]:
entrant_seeding = (
    entrant_ratings
    .filter(pl.col('rating').is_not_null())
    .sort('rating', descending=True)
    .with_row_index('seed_num')
    .with_columns(pl.col('seed_num') + 1)
)
entrant_seeding

shape: (23, 7)
┌──────────┬──────────┬─────────────────┬──────────────┬────────────────┬───────────┬──────────────┐
│ seed_num ┆ id       ┆ name            ┆ gamertag     ┆ url            ┆ rating    ┆ tag          │
│ ---      ┆ ---      ┆ ---             ┆ ---          ┆ ---            ┆ ---       ┆ ---          │
│ u32      ┆ i64      ┆ str             ┆ str          ┆ str            ┆ f64       ┆ str          │
╞══════════╪══════════╪═════════════════╪══════════════╪════════════════╪═══════════╪══════════════╡
│ 1        ┆ 20700362 ┆ regEx           ┆ regex        ┆ /league/nemele ┆ 36.301434 ┆ regex        │
│          ┆          ┆                 ┆              ┆ e/player/1D8B9 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ E3…            ┆           ┆              │
│ 2        ┆ 20687556 ┆ Ant             ┆ ant          ┆ /league/nemele ┆ 34.819169 ┆ ant          │
│          ┆          ┆                 ┆              ┆ e/player/5DBCC ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 34…            ┆           ┆              │
│ 3        ┆ 20699715 ┆ Karils |        ┆ conflict     ┆ /league/nemele ┆ 32.603542 ┆ conflict     │
│          ┆          ┆ Conflict        ┆              ┆ e/player/38A91 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 1E…            ┆           ┆              │
│ 4        ┆ 20698528 ┆ hc | saucymain  ┆ saucymain    ┆ /league/nemele ┆ 31.66636  ┆ saucymain    │
│          ┆          ┆                 ┆              ┆ e/player/2407F ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 41…            ┆           ┆              │
│ 5        ┆ 20696744 ┆ Sweat           ┆ sweat        ┆ /league/nemele ┆ 31.613687 ┆ sweat        │
│          ┆          ┆                 ┆              ┆ e/player/DF3CE ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 0B…            ┆           ┆              │
│ 6        ┆ 20701789 ┆ hc | kraft      ┆ kraft        ┆ /league/nemele ┆ 31.226735 ┆ kraft        │
│          ┆          ┆                 ┆              ┆ e/player/0CDB1 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 1B…            ┆           ┆              │
│ 7        ┆ 20701782 ┆ BonkCushy       ┆ bonkcushy    ┆ /league/nemele ┆ 30.252516 ┆ bonkcushy    │
│          ┆          ┆                 ┆              ┆ e/player/10562 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 55…            ┆           ┆              │
│ 8        ┆ 20700995 ┆ ThunderPaste    ┆ thunderpaste ┆ /league/nemele ┆ 29.386891 ┆ thunderpaste │
│          ┆          ┆                 ┆              ┆ e/player/E5452 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 13…            ┆           ┆              │
│ 9        ┆ 20668097 ┆ zaubermaus      ┆ zaubermaus   ┆ /league/nemele ┆ 28.319641 ┆ zaubermaus   │
│          ┆          ┆                 ┆              ┆ e/player/66DEE ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 19…            ┆           ┆              │
│ 10       ┆ 20700952 ┆ Nico            ┆ nico         ┆ /league/nemele ┆ 28.08942  ┆ nico         │
│          ┆          ┆                 ┆              ┆ e/player/D4FE0 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 6C…            ┆           ┆              │
│ 11       ┆ 20700969 ┆ hc | Jeep God   ┆ jeep god     ┆ /league/nemele ┆ 27.157563 ┆ jeep god     │
│          ┆          ┆                 ┆              ┆ e/player/4990C ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 91…            ┆           ┆              │
│ 12       ┆ 20700993 ┆ hc | Pizza      ┆ pizza        ┆ /league/nemele ┆ 26.863282 ┆ pizza        │
│          ┆          ┆                 ┆              ┆ e/player/73AF5 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 0A…            ┆           ┆              │
│ 13       ┆ 20698084 ┆ hc | Babs       ┆ babs         ┆ /league/nemele ┆ 26.112673 ┆ babs         │
│          ┆          ┆                 ┆              ┆ e/player/03D1D ┆           ┆              │
│          ┆          ┆                 ┆              ┆ A3…            ┆           ┆              │
│ 14       ┆ 20700412 ┆ Sleeper         ┆ sleeper      ┆ /league/nemele ┆ 25.565583 ┆ sleeper      │
│          ┆          ┆                 ┆              ┆ e/player/44E0B ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 0C…            ┆           ┆              │
│ 15       ┆ 20699153 ┆ Qwerty          ┆ qwerty       ┆ /league/nemele ┆ 25.0546   ┆ qwerty       │
│          ┆          ┆                 ┆              ┆ e/player/19B79 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ D7…            ┆           ┆              │
│ 16       ┆ 20687727 ┆ AUNTIE WOW |    ┆ bleop        ┆ /league/nemele ┆ 24.816556 ┆ bleop        │
│          ┆          ┆ bleop           ┆              ┆ e/player/9DABA ┆           ┆              │
│          ┆          ┆                 ┆              ┆ EA…            ┆           ┆              │
│ 17       ┆ 20701899 ┆ hc | pluto      ┆ pluto        ┆ /league/nemele ┆ 23.563623 ┆ pluto        │
│          ┆          ┆                 ┆              ┆ e/player/25B13 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 68…            ┆           ┆              │
│ 18       ┆ 20688969 ┆ yungsos         ┆ yungsos      ┆ /league/nemele ┆ 21.894614 ┆ yungsos      │
│          ┆          ┆                 ┆              ┆ e/player/BC547 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ FD…            ┆           ┆              │
│ 19       ┆ 20695615 ┆ Nuggetz         ┆ nuggetz      ┆ /league/nemele ┆ 19.90807  ┆ nuggetz      │
│          ┆          ┆                 ┆              ┆ e/player/DCB5F ┆           ┆              │
│          ┆          ┆                 ┆              ┆ A5…            ┆           ┆              │
│ 20       ┆ 20694180 ┆ Smyles          ┆ smyles       ┆ /league/nemele ┆ 18.81487  ┆ smyles       │
│          ┆          ┆                 ┆              ┆ e/player/24A07 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 1F…            ┆           ┆              │
│ 21       ┆ 20700136 ┆ Zeeb |          ┆ skynative    ┆ /league/nemele ┆ 17.843409 ┆ skynative    │
│          ┆          ┆ Skynative       ┆              ┆ e/player/34F14 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ CA…            ┆           ┆              │
│ 22       ┆ 20701804 ┆ MAIF            ┆ maif         ┆ /league/nemele ┆ 11.952874 ┆ maif         │
│          ┆          ┆                 ┆              ┆ e/player/36266 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ FF…            ┆           ┆              │
│ 23       ┆ 20691702 ┆ Exarch          ┆ exarch       ┆ /league/nemele ┆ 9.275028  ┆ exarch       │
│          ┆          ┆                 ┆              ┆ e/player/BD624 ┆           ┆              │
│          ┆          ┆                 ┆              ┆ 70…            ┆           ┆              │
└──────────┴──────────┴─────────────────┴──────────────┴────────────────┴───────────┴──────────────┘

# Export seeding to start gg

In [53]:
# Query to get phase IDs for Melee Singles event
phases_query = gql("""
query EventPhases($eventId: ID!) {
    event(id: $eventId) {
        phases {
            id
            name
            numSeeds
        }
    }
}
""")

phases_variables = {"eventId": melee_singles_id}

try:
        phases_result = client.execute(phases_query, variable_values=phases_variables)
        print(json.dumps(phases_result, indent=2))
except Exception as e:
        print("Error fetching phases:", e)

phase_id = phases_result['event']['phases'][0]['id']
print(f'phase id: {phase_id}')

{
  "event": {
    "phases": [
      {
        "id": 2021471,
        "name": "Bracket",
        "numSeeds": 30
      }
    ]
  }
}
phase id: 2021471

In [58]:
# Prepare seed mapping from entrant_ratings for the phase
seed_mapping = []
for row in entrant_seeding.iter_rows(named=True):
    seed_mapping.append({
        "seedId": row["id"],
        "seedNum": row['seed_num'],
    })

print(f"Importing {len(seed_mapping)} seeds to phase {phase_id}...")

mutation = gql("""
mutation UpdatePhaseSeeding($phaseId: ID!, $seedMapping: [UpdatePhaseSeedInfo]!) {
  updatePhaseSeeding(phaseId: $phaseId, seedMapping: $seedMapping) {
    id
  }
}
""")

params = {
    "phaseId": phase_id,
    "seedMapping": seed_mapping,
}

try:
    result = client.execute(mutation, variable_values=params)
    print('Success!')
    print(result)
except Exception as e:
    print('Error:', e)

Importing 23 seeds to phase 2021471...
Error: {'message': 'Cannot modify seeds in started pools', 'extensions': {'category': 'validation'}, 'locations': [{'line': 2, 'column': 3}], 'path': ['updatePhaseSeeding'], 'type': 'validation', 'fields': None, 'fieldErrors': []}