In [1]:
import polars as pl
import trueskill

## Create player dataframe

In [2]:
matches = pl.read_csv('data/matches.csv')

In [3]:
players = (
    matches
    .select(pl.col('winner').alias('tag'), pl.col('winner_url').alias('url'), 'tournament_date')
    .vstack(
        matches
        .select(pl.col('loser').alias('tag'), pl.col('loser_url').alias('url'), 'tournament_date')
    )
    .sort('tournament_date', descending=True)
    .group_by('url')
    #.agg(pl.col('tag').mode().first())
    .agg(pl.col('tag').first())
    .select('tag', 'url')
)
pl.Config(tbl_rows=2)
players

shape: (2_543, 2)
┌────────────────┬─────────────────────────────────┐
│ tag            ┆ url                             │
│ ---            ┆ ---                             │
│ str            ┆ str                             │
╞════════════════╪═════════════════════════════════╡
│ HSG | RyuCloud ┆ /league/nemelee/player/6CB2416… │
│ …              ┆ …                               │
│ Rez            ┆ /league/nemelee/player/FADB202… │
└────────────────┴─────────────────────────────────┘

# Calculate trueskill

In [4]:
pl.Config(tbl_rows=2)
matches

shape: (57_672, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ encounter ┆ winner_ur ┆ winner    ┆ loser_url ┆ … ┆ tournamen ┆ tournamen ┆ tournamen ┆ tourname │
│ _id       ┆ l         ┆ ---       ┆ ---       ┆   ┆ t_date    ┆ t_country ┆ t_region  ┆ nt_numbe │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ r_of_pla │
│ i64       ┆ str       ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ yers     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 13        ┆ /league/n ┆ Future    ┆ /league/n ┆ … ┆ 2025-02-1 ┆ null      ┆ null      ┆ null     │
│           ┆ emelee/pl ┆ Shock     ┆ emelee/pl ┆   ┆ 2         ┆           ┆           ┆          │
│           ┆ ayer/5CD3 ┆           ┆ ayer/118E ┆   ┆           ┆           ┆           ┆          │
│           ┆ DDF…      ┆           ┆ 203…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 34        ┆ /league/n ┆ Oasis |   ┆ /league/n ┆ … ┆ 2025-02-0 ┆ null      ┆ null      ┆ null     │
│           ┆ emelee/pl ┆ thronebut ┆ emelee/pl ┆   ┆ 1         ┆           ┆           ┆          │
│           ┆ ayer/ECE5 ┆ t         ┆ ayer/67C3 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09E…      ┆           ┆ 430…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
players_dict = {}

def rate_players(row: dict) -> dict:
    # Create TrueSkill rating objects for the players
    if players_dict.get(row['winner_url']) is None:
        players_dict[row['winner_url']] = trueskill.Rating()
    if players_dict.get(row['loser_url']) is None:
        players_dict[row['loser_url']] = trueskill.Rating()

    result = {
        'winner_rating': players_dict[row['winner_url']],
        'loser_rating': players_dict[row['loser_url']],
    }

    # Update the ratings based on the match outcome
    new_winner_rating, new_loser_rating = trueskill.rate_1vs1(
        players_dict[row['winner_url']], players_dict[row['loser_url']])
    players_dict[row['winner_url']] = new_winner_rating
    players_dict[row['loser_url']] = new_loser_rating

    result.update({
        'new_winner_rating': new_winner_rating,
        'new_loser_rating': new_loser_rating,
    })
    return result

In [6]:
players_dict = {}

matches_with_ratings = matches.with_columns(
    pl.struct(['winner_url', 'loser_url'])
        .map_elements(rate_players)
        .alias('new_ratings')
).unnest('new_ratings')

/tmp/ipykernel_25950/2286493820.py:3: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  matches_with_ratings = matches.with_columns(

## 95 CI
In TrueSkill, rating is a Gaussian distribution which starts from $\mathcal{ N }( 25, \frac{ 25 }{ 3 }^2 )$. $\mu$ is an average skill of player, and $\sigma$ is a confidence of the guessed rating. A real skill of player is between $\mu \pm 2\sigma$ with 95% confidence.

In [7]:
matches_with_ratings.write_csv('data/matches-with-ratings.csv')

## Export ranking

In [8]:
player_ratings = pl.DataFrame({
    'url': [player_url for player_url in players_dict.keys()],
    'rating': [rating for rating in players_dict.values()],
}).join(players, on='url').sort('rating', descending=True)

In [9]:
pl.Config(fmt_str_lengths=100)
players.filter(pl.col('tag').str.contains('dad'))

shape: (2, 2)
┌─────────────────┬──────────────────────────────────────────────────────────────┐
│ tag             ┆ url                                                          │
│ ---             ┆ ---                                                          │
│ str             ┆ str                                                          │
╞═════════════════╪══════════════════════════════════════════════════════════════╡
│ Stacy's Stepdad ┆ /league/nemelee/player/EC16A4A0-715F-4675-8C89-C60E61BE85AE? │
│ Sukisdad        ┆ /league/nemelee/player/8FC3E638-90E0-4E99-89F9-E4889E598ED0? │
└─────────────────┴──────────────────────────────────────────────────────────────┘

In [10]:
pl.Config(tbl_rows=50)
player_ratings.write_parquet('data/player-ratings.parquet')
player_ratings

shape: (2_542, 3)
┌───────────────────────────────────────────────────────────┬───────────┬──────────────────────────┐
│ url                                                       ┆ rating    ┆ tag                      │
│ ---                                                       ┆ ---       ┆ ---                      │
│ str                                                       ┆ f64       ┆ str                      │
╞═══════════════════════════════════════════════════════════╪═══════════╪══════════════════════════╡
│ /league/nemelee/player/FDFA0C9E-494A-41D2-8265-81EF222574 ┆ 49.307943 ┆ Nouns | Aklo             │
│ 20?                                                       ┆           ┆                          │
│ /league/nemelee/player/566A0261-78BE-4E0E-90D7-6AAB8F80F3 ┆ 48.230045 ┆ DTL | 2Saint             │
│ 82?                                                       ┆           ┆                          │
│ /league/nemelee/player/CCE3966C-52B8-41F9-8856-2847D64081 ┆ 45.347805 ┆ FLY | Jmook              │
│ EA?                                                       ┆           ┆                          │
│ /league/nemelee/player/891E8617-D369-4779-B91C-97D6884876 ┆ 45.183015 ┆ RedBull GG IFM | aMSa    │
│ 49?                                                       ┆           ┆                          │
│ /league/nemelee/player/37B32036-577A-4E74-A722-82E5993BC5 ┆ 44.684698 ┆ Spark                    │
│ 79?                                                       ┆           ┆                          │
│ /league/nemelee/player/2F70A3C4-A70B-4C95-89F4-9830B4B85B ┆ 44.593335 ┆ TC | Zanya               │
│ 37?                                                       ┆           ┆                          │
│ /league/nemelee/player/8CFD18F4-2E97-48BE-BA51-D243B5489A ┆ 44.548854 ┆ SDJ                      │
│ 36?                                                       ┆           ┆                          │
│ /league/nemelee/player/30D4C0A9-BF00-44C1-925F-2AC114611B ┆ 44.184032 ┆ SHDJ | Mekk              │
│ 57?                                                       ┆           ┆                          │
│ /league/nemelee/player/EB30F2BE-0BC5-4180-8302-EADAF60BDE ┆ 43.923601 ┆ Inky                     │
│ 40?                                                       ┆           ┆                          │
│ /league/nemelee/player/F7441D6E-6DB4-4BBB-8F3E-B2EB0DFA53 ┆ 43.854285 ┆ Epoodle                  │
│ 3B?                                                       ┆           ┆                          │
│ /league/nemelee/player/6B2BEB69-DCE1-4095-BFED-4F3205CF3C ┆ 43.835165 ┆ DrLobster                │
│ DB?                                                       ┆           ┆                          │
│ /league/nemelee/player/726A52BC-CF5A-4F17-A5EF-4604CC318F ┆ 43.527977 ┆ YAMI                     │
│ 03?                                                       ┆           ┆                          │
│ /league/nemelee/player/C2069576-DB5B-42E0-9C4B-31182802A6 ┆ 43.498531 ┆ MATE | Kalvar            │
│ 0F?                                                       ┆           ┆                          │
│ /league/nemelee/player/B9BE39AC-62DB-4385-A809-6AEB2740E5 ┆ 43.42347  ┆ max                      │
│ 99?                                                       ┆           ┆                          │
│ /league/nemelee/player/D861C5C8-2B42-4AB6-8649-6256E0EEF6 ┆ 42.730338 ┆ Kacey                    │
│ E5?                                                       ┆           ┆                          │
│ /league/nemelee/player/0ED0B111-D617-4E32-B2CA-9004A4BAAA ┆ 42.557582 ┆ PBI | Bekvin             │
│ 22?                                                       ┆           ┆                          │
│ /league/nemelee/player/C9B8492C-13D2-4D31-A7ED-A798212062 ┆ 42.485878 ┆ bonfire10                │
│ 67?                                                       ┆           ┆                          │
│ /league/nemelee/player/E9236ABC-8BDA-4A2C-9C98-CA74C3F69D ┆ 42.400823 ┆ MF | KoDoRiN             │
│ 6D?                                                       ┆           ┆                          │
│ /league/nemelee/player/197387D6-01AC-48CD-B6D5-DC529845ED ┆ 42.338044 ┆ TLOC | Salt              │
│ B4?                                                       ┆           ┆                          │
│ /league/nemelee/player/1D3EACBB-6B90-4C45-8A5F-034893BA94 ┆ 41.8948   ┆ Goodie                   │
│ 96?                                                       ┆           ┆                          │
│ /league/nemelee/player/27CF9E7D-F2DE-4126-B620-3D76454E46 ┆ 41.791102 ┆ BLITZ | PSA | Kikoho     │
│ 3C?                                                       ┆           ┆                          │
│ /league/nemelee/player/CFC19F8A-9EA3-4A43-8A27-A0C7F42C39 ┆ 41.592439 ┆ HPR                      │
│ F4?                                                       ┆           ┆                          │
│ /league/nemelee/player/853AD99B-0960-4AE3-9C81-C1D0F4EB74 ┆ 41.513373 ┆ 404Cray                  │
│ 3B?                                                       ┆           ┆                          │
│ /league/nemelee/player/4C2B18BA-75A9-45ED-A8B6-8D891297E0 ┆ 41.462508 ┆ LG | Louis               │
│ 0A?                                                       ┆           ┆                          │
│ /league/nemelee/player/A30A6D5E-FC8B-4453-8190-F5E6721DA6 ┆ 41.372252 ┆ Chem                     │
│ 00?                                                       ┆           ┆                          │
│ …                                                         ┆ …         ┆ …                        │
│ /league/nemelee/player/BFA3CBC8-7F48-4A67-B10B-82E248D235 ┆ 7.892455  ┆ corvo                    │
│ 8C?                                                       ┆           ┆                          │
│ /league/nemelee/player/06139B86-A88C-4F74-8690-9D14E33D8F ┆ 7.835712  ┆ Skel                     │
│ E7?                                                       ┆           ┆                          │
│ /league/nemelee/player/EC56A2A6-1A39-40C1-A564-B2D2ABB1C9 ┆ 7.707932  ┆ N0va | Breathlessx22     │
│ 4E?                                                       ┆           ┆                          │
│ /league/nemelee/player/40F574EF-457B-4112-A44B-A000E7A1A9 ┆ 7.587631  ┆ PLAID                    │
│ F5?                                                       ┆           ┆                          │
│ /league/nemelee/player/12A217E5-90E2-403B-9E49-5BC1EC3462 ┆ 7.570206  ┆ zweeP                    │
│ 78?                                                       ┆           ┆                          │
│ /league/nemelee/player/EBD45032-E336-437B-9851-B727DCB909 ┆ 7.342169  ┆ SirMichael               │
│ F4?                                                       ┆           ┆                          │
│ /league/nemelee/player/A1ECE312-A91A-4996-B885-138E7A5C22 ┆ 7.325636  ┆ Lua                      │
│ B7?                                                       ┆           ┆                          │
│ /league/nemelee/player/4EFF18B5-79B7-4715-83F6-2DD27AE495 ┆ 7.255362  ┆ Aeacus                   │
│ A7?                                                       ┆           ┆                          │
│ /league/nemelee/player/081AFCF9-DB42-4431-B2DC-08859ED453 ┆ 7.203214  ┆ Kilroy                   │
│ A2?                                                       ┆           ┆                          │
│ /league/nemelee/player/38547A80-778E-4BBC-8900-7098D6C176 ┆ 7.128275  ┆ Zeas44                   │
│ 06?                                                       ┆           ┆                          │
│ /league/nemelee/player/6C5E4981-2DF8-4C2E-B642-7E34CB37B0 ┆ 7.122368  ┆ eemee                    │
│ 04?                                                       ┆           ┆                          │
│ /league/nemelee/player/3691AF40-31C5-42A5-A395-06E456E20A ┆ 6.934715  ┆ TD | U4iK                │
│ 7C?                                                       ┆           ┆                          │
│ /league/nemelee/player/B6859533-90D0-454B-AA13-F7FB85D91D ┆ 6.91171   ┆ ShnooksNcookS            │
│ CE?                                                       ┆           ┆                          │
│ /league/nemelee/player/3372A46D-4CDB-4B61-96E8-D59D215C56 ┆ 6.805532  ┆ Liquid | Julzz           │
│ 38?                                                       ┆           ┆                          │
│ /league/nemelee/player/A3A96A71-220E-40A2-882C-02B36F7602 ┆ 6.731225  ┆ yamir                    │
│ C1?                                                       ┆           ┆                          │
│ /league/nemelee/player/137F1178-EBD5-441A-8E7F-C4CB79E87C ┆ 6.66938   ┆ crash0ut | StarDestiny34 │
│ DE?                                                       ┆           ┆                          │
│ /league/nemelee/player/7093E8EE-445C-4D47-B01A-4403DCEA3D ┆ 6.635586  ┆ Liquid Llama             │
│ 45?                                                       ┆           ┆                          │
│ /league/nemelee/player/95C74874-C1AE-4212-A273-5D1F579688 ┆ 6.597239  ┆ AK Sparx                 │
│ 6F?                                                       ┆           ┆                          │
│ /league/nemelee/player/D4EF54C7-C771-492A-96E4-A699A67477 ┆ 6.545463  ┆ Cryonova                 │
│ A1?                                                       ┆           ┆                          │
│ /league/nemelee/player/DF78D179-5121-4255-895D-F36DB238BA ┆ 6.202458  ┆ Julia                    │
│ 3C?                                                       ┆           ┆                          │
│ /league/nemelee/player/CEF9C72F-9AB1-4BC6-A570-3E7A6D08B3 ┆ 6.078272  ┆ Uncle Fraski             │
│ 49?                                                       ┆           ┆                          │
│ /league/nemelee/player/FF81A858-E20C-4CB3-93FF-DDE8BDCA9C ┆ 5.703817  ┆ ZeperTheStar             │
│ DD?                                                       ┆           ┆                          │
│ /league/nemelee/player/A4AB22F7-57D5-41F7-851C-8429E55049 ┆ 5.301837  ┆ RosieCo | Pure           │
│ 71?                                                       ┆           ┆                          │
│ /league/nemelee/player/D0BD45DD-50F5-40DD-9E4E-169F9C6691 ┆ 5.257906  ┆ crash0ut | Awkward.      │
│ 5D?                                                       ┆           ┆                          │
│ /league/nemelee/player/D88C9BF6-42FB-4064-ADC9-CA42C38244 ┆ 4.482152  ┆ IDGM                     │
│ 0B?                                                       ┆           ┆                          │
└───────────────────────────────────────────────────────────┴───────────┴──────────────────────────┘

In [11]:
import plotly.express as px

player_tag = ''

player_matches = (
    matches_with_ratings.filter(
        (pl.col('winner') == player_tag) |
        (pl.col('loser') == player_tag)
    )
    .select(
        'winner', 'loser',
        'tournament_date',
        pl.when(pl.col('winner') == player_tag).then(pl.col('new_winner_rating'))
        .otherwise(pl.col('new_loser_rating'))
        .alias('rating'),
    )
    .sort('tournament_date')
)

# Create the plot
px.line(
    data_frame=player_matches.to_pandas(),
    x='tournament_date',
    y='rating',
    labels={'x': 'Date', 'y': 'TrueSkill Rating (μ)'},
    title=f"Rating Progression: {player_tag}"
)