In [15]:
import polars as pl
import trueskill

## Create player dataframe

In [24]:
matches = pl.read_csv('data/matches.csv')

In [43]:
players = (
    matches
    .select(pl.col('winner').alias('tag'), pl.col('winner_url').alias('url'), 'tournament_date')
    .vstack(
        matches
        .select(pl.col('loser').alias('tag'), pl.col('loser_url').alias('url'), 'tournament_date')
    )
    .sort('tournament_date', descending=True)
    .group_by('url')
    #.agg(pl.col('tag').mode().first())
    .agg(pl.col('tag').first())
    .select('tag', 'url')
)
pl.Config(tbl_rows=2)
players

shape: (2_261, 2)
┌───────┬─────────────────────────────────┐
│ tag   ┆ url                             │
│ ---   ┆ ---                             │
│ str   ┆ str                             │
╞═══════╪═════════════════════════════════╡
│ Dour  ┆ /league/nemelee/player/68A7DE4… │
│ …     ┆ …                               │
│ James ┆ /league/nemelee/player/F2732F6… │
└───────┴─────────────────────────────────┘

# Calculate trueskill

In [44]:
pl.Config(tbl_rows=2)
matches

shape: (46_978, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ encounter ┆ winner_ur ┆ winner    ┆ loser_url ┆ … ┆ tournamen ┆ tournamen ┆ tournamen ┆ tourname │
│ _id       ┆ l         ┆ ---       ┆ ---       ┆   ┆ t_date    ┆ t_country ┆ t_region  ┆ nt_numbe │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ r_of_pla │
│ i64       ┆ str       ┆           ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ yers     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 54        ┆ /league/n ┆ hc | Nvr  ┆ /league/n ┆ … ┆ 2025-04-0 ┆ null      ┆ null      ┆ null     │
│           ┆ emelee/pl ┆ regret    ┆ emelee/pl ┆   ┆ 8         ┆           ┆           ┆          │
│           ┆ ayer/ACFD ┆ grwing    ┆ ayer/BC54 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 51E…      ┆ flowrs    ┆ 7FD…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 64        ┆ /league/n ┆ WAS | 22K ┆ /league/n ┆ … ┆ 2023-01-2 ┆ null      ┆ null      ┆ null     │
│           ┆ emelee/pl ┆           ┆ emelee/pl ┆   ┆ 5         ┆           ┆           ┆          │
│           ┆ ayer/11CA ┆           ┆ ayer/01B9 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20C…      ┆           ┆ 633…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
players_dict = {}

def rate_players(row: dict) -> dict:
    # Create TrueSkill rating objects for the players
    if players_dict.get(row['winner_url']) is None:
        players_dict[row['winner_url']] = trueskill.Rating()
    if players_dict.get(row['loser_url']) is None:
        players_dict[row['loser_url']] = trueskill.Rating()

    result = {
        'winner_rating': players_dict[row['winner_url']],
        'loser_rating': players_dict[row['loser_url']],
    }

    # Update the ratings based on the match outcome
    new_winner_rating, new_loser_rating = trueskill.rate_1vs1(
        players_dict[row['winner_url']], players_dict[row['loser_url']])
    players_dict[row['winner_url']] = new_winner_rating
    players_dict[row['loser_url']] = new_loser_rating

    result.update({
        'new_winner_rating': new_winner_rating,
        'new_loser_rating': new_loser_rating,
    })
    return result

In [46]:
players_dict = {}

matches_with_ratings = matches.with_columns(
    pl.struct(['winner_url', 'loser_url'])
        .map_elements(rate_players)
        .alias('new_ratings')
).unnest('new_ratings')

/tmp/ipykernel_30341/2286493820.py:3: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  matches_with_ratings = matches.with_columns(

## 95 CI
In TrueSkill, rating is a Gaussian distribution which starts from $\mathcal{ N }( 25, \frac{ 25 }{ 3 }^2 )$. $\mu$ is an average skill of player, and $\sigma$ is a confidence of the guessed rating. A real skill of player is between $\mu \pm 2\sigma$ with 95% confidence.

In [47]:
matches_with_ratings.write_csv('data/matches-with-ratings.csv')

## Export ranking

In [48]:
player_ratings = pl.DataFrame({
    'url': [player_url for player_url in players_dict.keys()],
    'rating': [rating for rating in players_dict.values()],
}).join(players, on='url').sort('rating', descending=True)

In [49]:
pl.Config(tbl_rows=50)
player_ratings.write_parquet('data/player-ratings.parquet')
player_ratings

shape: (2_260, 3)
┌─────────────────────────────────┬───────────┬─────────────────────────────────┐
│ url                             ┆ rating    ┆ tag                             │
│ ---                             ┆ ---       ┆ ---                             │
│ str                             ┆ f64       ┆ str                             │
╞═════════════════════════════════╪═══════════╪═════════════════════════════════╡
│ /league/nemelee/player/FDFA0C9… ┆ 48.278555 ┆ Nouns | Aklo                    │
│ /league/nemelee/player/891E861… ┆ 46.742295 ┆ RedBull GG IFM | aMSa           │
│ /league/nemelee/player/566A026… ┆ 46.084774 ┆ DTL | 2Saint                    │
│ /league/nemelee/player/37B3203… ┆ 45.802308 ┆ Spark                           │
│ /league/nemelee/player/C206957… ┆ 44.604296 ┆ MATE | Kalvar                   │
│ /league/nemelee/player/F7441D6… ┆ 44.513993 ┆ Epoodle                         │
│ /league/nemelee/player/6B2BEB6… ┆ 44.390449 ┆ DrLobster                       │
│ /league/nemelee/player/30D4C0A… ┆ 43.930801 ┆ SHDJ | Mekk                     │
│ /league/nemelee/player/2F70A3C… ┆ 43.890449 ┆ TC | Zanya                      │
│ /league/nemelee/player/D861C5C… ┆ 43.229008 ┆ Kacey                           │
│ /league/nemelee/player/B9BE39A… ┆ 42.995607 ┆ max                             │
│ /league/nemelee/player/197387D… ┆ 42.418718 ┆ TLOC | Salt                     │
│ /league/nemelee/player/726A52B… ┆ 42.282301 ┆ YAMI                            │
│ /league/nemelee/player/A30A6D5… ┆ 42.153013 ┆ Chem                            │
│ /league/nemelee/player/37727CD… ┆ 42.011498 ┆ Chef Rach                       │
│ /league/nemelee/player/853AD99… ┆ 41.956439 ┆ 404Cray                         │
│ /league/nemelee/player/7BAB605… ┆ 41.894144 ┆ Squid                           │
│ /league/nemelee/player/DC23337… ┆ 41.870791 ┆ Panda                           │
│ /league/nemelee/player/C9B8492… ┆ 41.865965 ┆ bonfire10                       │
│ /league/nemelee/player/0ED0B11… ┆ 41.759264 ┆ PBI | Bekvin                    │
│ /league/nemelee/player/EB30F2B… ┆ 41.6423   ┆ Inky                            │
│ /league/nemelee/player/27CF9E7… ┆ 41.457894 ┆ BLITZ | PSA | Kikoho            │
│ /league/nemelee/player/738F1C1… ┆ 41.375758 ┆ sorry | essy                    │
│ /league/nemelee/player/1D3EACB… ┆ 41.27051  ┆ Goodie                          │
│ /league/nemelee/player/CFC19F8… ┆ 41.252455 ┆ HPR                             │
│ …                               ┆ …         ┆ …                               │
│ /league/nemelee/player/69E277D… ┆ 7.94779   ┆ Corbulon                        │
│ /league/nemelee/player/2BC9EDC… ┆ 7.745143  ┆ Dorothy                         │
│ /league/nemelee/player/EBD4503… ┆ 7.714144  ┆ SirMichael                      │
│ /league/nemelee/player/EC56A2A… ┆ 7.712335  ┆ N0va | Breathlessx22            │
│ /league/nemelee/player/7093E8E… ┆ 7.60204   ┆ Liquid Llama                    │
│ /league/nemelee/player/A1ECE31… ┆ 7.548487  ┆ Lua                             │
│ /league/nemelee/player/AEE5BDB… ┆ 7.537345  ┆ Feed's Friend | Monotone Culpr… │
│ /league/nemelee/player/12A217E… ┆ 7.318626  ┆ zweeP                           │
│ /league/nemelee/player/4EFF18B… ┆ 7.26985   ┆ Aeacus                          │
│ /league/nemelee/player/95C7487… ┆ 7.242267  ┆ AK Sparx                        │
│ /league/nemelee/player/3691AF4… ┆ 7.222504  ┆ TD | U4iK                       │
│ /league/nemelee/player/F07E0A7… ┆ 7.040101  ┆ SwankyD                         │
│ /league/nemelee/player/D0BD45D… ┆ 6.967899  ┆ crash0ut | Awkward.             │
│ /league/nemelee/player/B685953… ┆ 6.883209  ┆ ShnooksNcookS                   │
│ /league/nemelee/player/1DBAAA1… ┆ 6.799825  ┆ JoeNut                          │
│ /league/nemelee/player/DA8A79E… ┆ 6.42206   ┆ Feed                            │
│ /league/nemelee/player/137F117… ┆ 6.303255  ┆ crash0ut | StarDestiny34        │
│ /league/nemelee/player/40F574E… ┆ 6.239143  ┆ PLAID                           │
│ /league/nemelee/player/6C5E498… ┆ 6.203977  ┆ eemee                           │
│ /league/nemelee/player/3372A46… ┆ 5.540263  ┆ Liquid | Julzz                  │
│ /league/nemelee/player/DF78D17… ┆ 5.448713  ┆ Julia                           │
│ /league/nemelee/player/D4EF54C… ┆ 5.437659  ┆ Cryonova                        │
│ /league/nemelee/player/FF81A85… ┆ 5.231722  ┆ ZeperTheStar                    │
│ /league/nemelee/player/A4AB22F… ┆ 5.175811  ┆ RosieCo | Pure                  │
│ /league/nemelee/player/D88C9BF… ┆ 3.599496  ┆ IDGM                            │
└─────────────────────────────────┴───────────┴─────────────────────────────────┘