In [1]:
import os
import re

# This script is used to set the working directory to the root of the project.
cwd = os.getcwd()
project_name = 'braacket-scraper'
project_root = re.split(rf'(?!.*({project_name}))/(.+)$', cwd)[0]
os.chdir(project_root)
project_root

'/home/agiera/ssbm/braacket-scraper'

In [2]:
import ipywidgets as widgets
import polars as pl
import trueskill
import rating_utils

In [17]:
year_before_season = '2023-11-03'
season_start = '2024-11-03'
season_end = '2025-04-19'

In [ ]:
candidates = pl.DataFrame([
    ["/league/nemelee/player/97D40D09-E9DF-468E-B90B-DD42CA8FA878?", "Younger"],
    ["/league/nemelee/player/583438BD-F9A1-413A-8F77-DEF3820143F0?", "N0va | hc | Coolslice"],
    ["/league/nemelee/player/BAB54F38-444F-4ADE-8D79-EC7D232D90E9?", "OUG | Electroman"],
    ["/league/nemelee/player/1D8B9E33-86AE-45FB-89E9-0CB158C24FD3?", "regEx"],
    ["/league/nemelee/player/39E544D6-60EC-4243-829E-C0E017FD58DC?", "s6 | shmeeli"],
    ["/league/nemelee/player/0267F6B4-223B-4D0D-B0AB-3B7084B37AB7?", "Greenstach"],
    ["/league/nemelee/player/EAE5E0CC-99FF-49EB-8424-142348454761?", "Comcast | The CoveCare Scare"],
    ["/league/nemelee/player/E85EE0F4-C335-4A1C-A569-BE69C1675BAA?", "$G|MP | Bank"],
    ["/league/nemelee/player/2407F41F-64A0-43AF-85F1-96F6985E57EE?", "hc | saucymain"],
    ["/league/nemelee/player/5CD3DDFC-6380-4395-8DF7-590D498437E2?", "Future Shock"],
    ["/league/nemelee/player/D3B00EC5-2479-4E29-8FBE-32DEEFFD23D2?", "Nage"],
    ["/league/nemelee/player/5DBCC342-92B6-40C6-AFBF-66933EF41379?", "Ant"],
    ["/league/nemelee/player/11CA20C1-5FDF-4A64-BC6C-0B5B91497FE7?", "MATE | 22K"],
    ["/league/nemelee/player/FA73F3AA-3D89-4584-A3D3-3E44E4B61180?", "Rat Rattington"],
    ["/league/nemelee/player/17A43CB7-E905-4A9A-A69A-55CC66EE929E?", "Bin/BTR | Yousef"],
    ["/league/nemelee/player/0CDB11B1-BCC3-4027-90F2-D74F1A9A5668?", "hc | kraft"],
    ["/league/nemelee/player/0D8C1F36-D79B-4FEF-91DE-5963AC99D13D?", "MEAT"],
], orient="row", schema=["url", "tag"])
candidate_urls = candidates.select('url').to_series().to_list()


# Load Data

In [6]:
matches = pl.read_csv("data/matches.csv")
season_matches = (
    matches
    .filter(pl.col('tournament_date') >= season_start)
    .filter(pl.col('tournament_date') <= season_end)
)

## Using just season data

In [7]:
season_matches_with_ratings = rating_utils.calculate_ratings(matches, season_start, season_end)
season_player_ratings = rating_utils.get_final_ratings(season_matches_with_ratings)
pl.Config(tbl_rows=20)
season_player_ratings.filter(pl.col('url').is_in(candidates.select('url').to_series().to_list()))

shape: (17, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ starting_ ┆ rating    ┆ rating_95 ┆ … ┆ exposure  ┆ tournamen ┆ encounter ┆ tag      │
│ ---       ┆ rating    ┆ ---       ┆ ci_lower  ┆   ┆ ---       ┆ t_date    ┆ _id       ┆ ---      │
│ str       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ str      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆           ┆ str       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ /league/n ┆ 38.574333 ┆ 39.180594 ┆ 33.411702 ┆ … ┆ 30.527256 ┆ 2025-04-1 ┆ 13        ┆ N0va |   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ hc | Coo │
│ ayer/5834 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ lslice   │
│ 38B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 38.289763 ┆ 38.777887 ┆ 33.821568 ┆ … ┆ 31.343409 ┆ 2025-04-1 ┆ 82        ┆ Younger  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ ayer/97D4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0D0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 36.446046 ┆ 36.25874  ┆ 33.692048 ┆ … ┆ 32.408702 ┆ 2025-03-2 ┆ 115       ┆ regEx    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ ayer/1D8B ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9E3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 35.516288 ┆ 35.405498 ┆ 33.300237 ┆ … ┆ 32.247607 ┆ 2025-04-1 ┆ 72        ┆ Greensta │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ ch       │
│ ayer/0267 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F6B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.093789 ┆ 34.435413 ┆ 32.178628 ┆ … ┆ 31.050236 ┆ 2025-04-1 ┆ 32        ┆ Ant      │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ ayer/5DBC ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C34…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.712171 ┆ 34.348671 ┆ 30.602907 ┆ … ┆ 28.730025 ┆ 2025-04-0 ┆ 37        ┆ s6 |     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ shmeeli  │
│ ayer/39E5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 44D…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.201088 ┆ 34.173681 ┆ 32.302454 ┆ … ┆ 31.36684  ┆ 2025-04-1 ┆ 29        ┆ NEU |    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆ saucymai │
│ ayer/2407 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ n        │
│ F41…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 29.395832 ┆ 33.909214 ┆ 21.734261 ┆ … ┆ 15.646785 ┆ 2025-04-1 ┆ 17        ┆ OUG |    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆ Electrom │
│ ayer/BAB5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an       │
│ 4F3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.694569 ┆ 33.810303 ┆ 31.655813 ┆ … ┆ 30.578568 ┆ 2025-04-0 ┆ 42        ┆ Comcast  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ | The    │
│ ayer/EAE5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CoveCare │
│ E0C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Scare    │
│ /league/n ┆ 33.707176 ┆ 33.798439 ┆ 31.624127 ┆ … ┆ 30.536971 ┆ 2025-04-0 ┆ 16        ┆ Future   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆ Shock    │
│ ayer/5CD3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DDF…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.331964 ┆ 33.402134 ┆ 31.333807 ┆ … ┆ 30.299643 ┆ 2025-04-1 ┆ 43        ┆ MATE |   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ 22K      │
│ ayer/11CA ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.184707 ┆ 33.373819 ┆ 29.741647 ┆ … ┆ 27.925561 ┆ 2025-04-1 ┆ 29        ┆ Nage     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ ayer/D3B0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0EC…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.496654 ┆ 32.770377 ┆ 26.504026 ┆ … ┆ 23.37085  ┆ 2025-03-1 ┆ 335       ┆ $G|MP |  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ Bank     │
│ ayer/E85E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ E0F…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 31.836408 ┆ 32.757395 ┆ 28.03859  ┆ … ┆ 25.679188 ┆ 2025-04-0 ┆ 74        ┆ Bin/BTR  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ | Yousef │
│ ayer/17A4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3CB…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.480872 ┆ 30.723391 ┆ 23.585342 ┆ … ┆ 20.016318 ┆ 2025-03-0 ┆ 120       ┆ Rat Ratt │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ ington   │
│ ayer/FA73 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F3A…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 28.077004 ┆ 27.895003 ┆ 24.447491 ┆ … ┆ 22.723735 ┆ 2025-04-1 ┆ 67        ┆ hc |     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ kraft    │
│ ayer/0CDB ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 27.849133 ┆ 26.821813 ┆ 16.593302 ┆ … ┆ 11.479046 ┆ 2025-03-1 ┆ 168       ┆ MEAT     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆          │
│ ayer/0D8C ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1F3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Using data outside season for non candidates who didn't enter enough

In [18]:
matches_with_ratings = rating_utils.calculate_ratings(
    matches.filter(pl.col('tournament_date') > year_before_season),
    season_start, season_end, sigma_fix=2.0,
)

In [19]:
player_ratings = rating_utils.get_final_ratings(matches_with_ratings)

In [28]:
pl.Config(tbl_rows=20)
candidate_placings = (
    player_ratings
    .filter(pl.col('url').is_in(candidates.select('url').to_series().to_list()))
    .select(pl.exclude('url', 'pi', 'tau', 'exposure'))
)
candidate_placings

shape: (17, 8)
┌────────────┬───────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┐
│ starting_r ┆ rating    ┆ rating_95c ┆ rating_95c ┆ sigma    ┆ tournament ┆ encounter ┆ tag       │
│ ating      ┆ ---       ┆ i_lower    ┆ i_upper    ┆ ---      ┆ _date      ┆ _id       ┆ ---       │
│ ---        ┆ f64       ┆ ---        ┆ ---        ┆ f64      ┆ ---        ┆ ---       ┆ str       │
│ f64        ┆           ┆ f64        ┆ f64        ┆          ┆ str        ┆ i64       ┆           │
╞════════════╪═══════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╡
│ 39.346681  ┆ 39.346681 ┆ 37.522335  ┆ 41.171027  ┆ 0.912173 ┆ 2025-03-16 ┆ 335       ┆ $G|MP |   │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Bank      │
│ 39.25371   ┆ 39.25371  ┆ 37.459867  ┆ 41.047553  ┆ 0.896922 ┆ 2025-04-19 ┆ 82        ┆ Younger   │
│ 37.529479  ┆ 37.394472 ┆ 35.308664  ┆ 39.48028   ┆ 1.042904 ┆ 2025-03-25 ┆ 115       ┆ regEx     │
│ 37.299468  ┆ 37.299468 ┆ 35.534151  ┆ 39.064785  ┆ 0.882658 ┆ 2025-04-19 ┆ 17        ┆ OUG | Ele │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ ctroman   │
│ 36.228441  ┆ 36.228441 ┆ 34.488722  ┆ 37.968161  ┆ 0.86986  ┆ 2025-03-01 ┆ 120       ┆ Rat Ratti │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ ngton     │
│ 35.974263  ┆ 35.860614 ┆ 33.816494  ┆ 37.904735  ┆ 1.02206  ┆ 2025-04-11 ┆ 72        ┆ Greenstac │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ h         │
│ 36.19633   ┆ 35.800102 ┆ 31.684852  ┆ 39.915352  ┆ 2.057625 ┆ 2025-04-05 ┆ 37        ┆ s6 |      │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ shmeeli   │
│ 35.607196  ┆ 35.607196 ┆ 33.801996  ┆ 37.412396  ┆ 0.9026   ┆ 2025-04-14 ┆ 13        ┆ N0va | hc │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ |         │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Coolslice │
│ 35.077808  ┆ 35.346569 ┆ 33.198365  ┆ 37.494772  ┆ 1.074102 ┆ 2025-04-15 ┆ 32        ┆ Ant       │
│ 35.13236   ┆ 35.097337 ┆ 33.203691  ┆ 36.990982  ┆ 0.946823 ┆ 2025-04-19 ┆ 29        ┆ NEU |     │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ saucymain │
│ 34.494162  ┆ 34.494162 ┆ 32.528838  ┆ 36.459486  ┆ 0.982662 ┆ 2025-03-16 ┆ 168       ┆ MEAT      │
│ 34.485154  ┆ 34.485154 ┆ 32.640071  ┆ 36.330238  ┆ 0.922542 ┆ 2025-04-19 ┆ 29        ┆ Nage      │
│ 34.124432  ┆ 34.217543 ┆ 32.112462  ┆ 36.322624  ┆ 1.05254  ┆ 2025-04-05 ┆ 42        ┆ Heavenly  │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Sunflower │
│ 34.13092   ┆ 34.13092  ┆ 32.113695  ┆ 36.148145  ┆ 1.008613 ┆ 2025-04-01 ┆ 74        ┆ Bin/BTR | │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Yousef    │
│ 33.856521  ┆ 33.970908 ┆ 31.841924  ┆ 36.099892  ┆ 1.064492 ┆ 2025-04-09 ┆ 16        ┆ Future    │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Shock     │
│ 32.563186  ┆ 32.563186 ┆ 30.80541   ┆ 34.320961  ┆ 0.878888 ┆ 2025-04-14 ┆ 43        ┆ MATE |    │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ 22K       │
│ 30.153543  ┆ 29.964461 ┆ 26.860488  ┆ 33.068434  ┆ 1.551986 ┆ 2025-04-15 ┆ 67        ┆ hc |      │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ kraft     │
└────────────┴───────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┘

In [21]:
matches_with_difference = (
    matches_with_ratings
    .join(player_ratings.select('url', pl.col('rating').alias('winner_final_rating')), left_on='winner_url', right_on='url')
    .join(player_ratings.select('url', pl.col('rating').alias('loser_final_rating')), left_on='loser_url', right_on='url')
    .with_columns((pl.col('winner_final_rating') - pl.col('loser_final_rating')).alias('final_rating_difference'))
    .select('winner_url', 'winner', 'winner_final_rating', 'loser_url', 'loser', 'loser_final_rating', 'final_rating_difference')
)

# Match Analysis

If some player's rating is higher $\beta$ than another player's, the player may have about a 76% (specifically $\Phi(\frac {1}{\sqrt{2}}))$ chance to beat the other player. The default value of $\beta$ is $\frac{ 25 }{ 6 }$.

## Wins in order of rating difference

In [22]:
def best_wins(matches: pl.DataFrame, player_url: str) -> pl.DataFrame:
    return (
        matches
        .filter(pl.col('winner_url').str.contains(player_url))
        .sort('final_rating_difference')
        .select(pl.exclude(r'^.*url$'))
        .select(pl.exclude(r'^winner.*$'))
        .head(100)
    )

## Losses in order of rating difference

In [23]:
def worst_losses(matches: pl.DataFrame, player_url: str) -> pl.DataFrame:
    return (
        matches
        .filter(pl.col('loser_url').str.contains(player_url))
        .select(pl.exclude(r'^.*url$'))
        .select(pl.exclude(r'^loser.*$'))
        .sort('final_rating_difference')
    )

In [24]:
def compare_players(matches: pl.DataFrame, player1: str, player2: str) -> pl.DataFrame:
    output1 = widgets.Output()
    output2 = widgets.Output()
    output3 = widgets.Output()
    output4 = widgets.Output()

    with output1:
        display(best_wins(matches, player1))
    with output2:
        display(best_wins(matches, player2))
    with output3:
        display(worst_losses(matches, player1))
    with output4:
        display(worst_losses(matches, player2))

    win_columns = widgets.HBox([output1, output2])
    loss_columns = widgets.HBox([output3, output4])
    final_output = widgets.VBox([win_columns, loss_columns])

    display(final_output)

In [29]:
pl.Config(tbl_rows=100)
for i in range(0, len(candidate_urls) - 1):
    first_candidate = candidate_placings.slice(i, 1).select('tag').item()
    second_candidate = candidate_placings.slice(i+1, 1).select('tag').item()
    print(f"Comparing {first_candidate} and {second_candidate}")
    compare_players(matches_with_difference, candidate_urls[i], candidate_urls[i+1])

Comparing $G|MP | Bank and Younger

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Younger and regEx

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing regEx and OUG | Electroman

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing OUG | Electroman and Rat Rattington

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Rat Rattington and Greenstach

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Greenstach and s6 | shmeeli

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing s6 | shmeeli and N0va | hc | Coolslice

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing N0va | hc | Coolslice and Ant

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Ant and NEU | saucymain

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing NEU | saucymain and MEAT

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing MEAT and Nage

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Nage and Heavenly Sunflower

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Heavenly Sunflower and Bin/BTR | Yousef

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Bin/BTR | Yousef and Future Shock

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing Future Shock and MATE | 22K

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))

Comparing MATE | 22K and hc | kraft

VBox(children=(HBox(children=(Output(), Output())), HBox(children=(Output(), Output()))))