In [1]:
import os
import re

# This script is used to set the working directory to the root of the project.
cwd = os.getcwd()
project_name = 'braacket-scraper'
project_root = re.split(rf'(?!.*({project_name}))/(.+)$', cwd)[0]
os.chdir(project_root)
project_root

'/home/agiera/ssbm/braacket-scraper'

In [ ]:
import polars as pl
import rating_utils
from IPython.display import display, HTML

In [3]:
year_before_season = '2023-11-03'
season_start = '2024-11-03'
season_end = '2025-04-19'

In [4]:
candidates = pl.DataFrame([
    ["/league/nemelee/player/97D40D09-E9DF-468E-B90B-DD42CA8FA878?", "Younger"],
    ["/league/nemelee/player/583438BD-F9A1-413A-8F77-DEF3820143F0?", "N0va | hc | Coolslice"],
    ["/league/nemelee/player/BAB54F38-444F-4ADE-8D79-EC7D232D90E9?", "OUG | Electroman"],
    ["/league/nemelee/player/1D8B9E33-86AE-45FB-89E9-0CB158C24FD3?", "regEx"],
    ["/league/nemelee/player/39E544D6-60EC-4243-829E-C0E017FD58DC?", "s6 | shmeeli"],
    ["/league/nemelee/player/0267F6B4-223B-4D0D-B0AB-3B7084B37AB7?", "Greenstach"],
    ["/league/nemelee/player/EAE5E0CC-99FF-49EB-8424-142348454761?", "Comcast | The CoveCare Scare"],
    ["/league/nemelee/player/E85EE0F4-C335-4A1C-A569-BE69C1675BAA?", "$G|MP | Bank"],
    ["/league/nemelee/player/2407F41F-64A0-43AF-85F1-96F6985E57EE?", "hc | saucymain"],
    ["/league/nemelee/player/5CD3DDFC-6380-4395-8DF7-590D498437E2?", "Future Shock"],
    ["/league/nemelee/player/D3B00EC5-2479-4E29-8FBE-32DEEFFD23D2?", "Nage"],
    ["/league/nemelee/player/5DBCC342-92B6-40C6-AFBF-66933EF41379?", "Ant"],
    ["/league/nemelee/player/11CA20C1-5FDF-4A64-BC6C-0B5B91497FE7?", "MATE | 22K"],
    ["/league/nemelee/player/FA73F3AA-3D89-4584-A3D3-3E44E4B61180?", "Rat Rattington"],
    ["/league/nemelee/player/17A43CB7-E905-4A9A-A69A-55CC66EE929E?", "Bin/BTR | Yousef"],
    ["/league/nemelee/player/0CDB11B1-BCC3-4027-90F2-D74F1A9A5668?", "hc | kraft"],
    ["/league/nemelee/player/0D8C1F36-D79B-4FEF-91DE-5963AC99D13D?", "MEAT"],
], orient="row", schema=["url", "tag"])
candidate_urls = candidates.select('url').to_series().to_list()


# Load Data

In [5]:
matches = pl.read_csv("data/matches.csv")
season_matches = (
    matches
    .filter(pl.col('tournament_date') >= season_start)
    .filter(pl.col('tournament_date') <= season_end)
)

## Using just season data

In [6]:
season_matches_with_ratings = rating_utils.calculate_ratings(matches, season_start, season_end)
season_player_ratings = rating_utils.get_final_ratings(season_matches_with_ratings)
pl.Config(tbl_rows=20)
season_player_ratings.filter(pl.col('url').is_in(candidates.select('url').to_series().to_list()))

shape: (17, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ starting_ ┆ rating    ┆ rating_95 ┆ … ┆ exposure  ┆ tournamen ┆ encounter ┆ tag      │
│ ---       ┆ rating    ┆ ---       ┆ ci_lower  ┆   ┆ ---       ┆ t_date    ┆ _id       ┆ ---      │
│ str       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ str      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆           ┆ str       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ /league/n ┆ 37.456669 ┆ 38.412727 ┆ 32.491756 ┆ … ┆ 29.53127  ┆ 2025-04-1 ┆ 82        ┆ Younger  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ ayer/97D4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0D0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 36.267178 ┆ 37.062354 ┆ 31.456592 ┆ … ┆ 28.653711 ┆ 2025-04-1 ┆ 13        ┆ N0va |   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ hc | Coo │
│ ayer/5834 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ lslice   │
│ 38B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 37.299927 ┆ 36.560171 ┆ 32.344147 ┆ … ┆ 30.236135 ┆ 2025-03-1 ┆ 168       ┆ MEAT     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆          │
│ ayer/0D8C ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1F3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 35.927092 ┆ 35.806591 ┆ 33.755006 ┆ … ┆ 32.729213 ┆ 2025-03-2 ┆ 115       ┆ regEx    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ ayer/1D8B ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9E3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 35.223688 ┆ 35.560322 ┆ 32.430224 ┆ … ┆ 30.865176 ┆ 2025-04-1 ┆ 17        ┆ OUG |    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆ Electrom │
│ ayer/BAB5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an       │
│ 4F3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.595606 ┆ 35.072809 ┆ 30.362943 ┆ … ┆ 28.00801  ┆ 2025-04-1 ┆ 29        ┆ Nage     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ ayer/D3B0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0EC…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 35.182258 ┆ 34.879267 ┆ 30.932071 ┆ … ┆ 28.958473 ┆ 2025-04-0 ┆ 37        ┆ s6 |     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ shmeeli  │
│ ayer/39E5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 44D…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.811138 ┆ 33.944268 ┆ 31.72041  ┆ … ┆ 30.608481 ┆ 2025-04-0 ┆ 16        ┆ Future   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆ Shock    │
│ ayer/5CD3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DDF…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.001862 ┆ 33.641832 ┆ 30.111844 ┆ … ┆ 28.34685  ┆ 2025-04-1 ┆ 72        ┆ Greensta │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ ch       │
│ ayer/0267 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F6B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.892115 ┆ 33.627652 ┆ 30.755314 ┆ … ┆ 29.319145 ┆ 2025-04-1 ┆ 29        ┆ NEU |    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆ saucymai │
│ ayer/2407 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ n        │
│ F41…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.90736  ┆ 33.393012 ┆ 28.617834 ┆ … ┆ 26.230245 ┆ 2025-04-1 ┆ 43        ┆ MATE |   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆ 22K      │
│ ayer/11CA ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.972623 ┆ 33.063537 ┆ 26.29852  ┆ … ┆ 22.916012 ┆ 2025-03-1 ┆ 335       ┆ $G|MP |  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆ Bank     │
│ ayer/E85E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ E0F…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.567565 ┆ 32.928524 ┆ 29.678856 ┆ … ┆ 28.054022 ┆ 2025-04-0 ┆ 42        ┆ Comcast  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ | The    │
│ ayer/EAE5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CoveCare │
│ E0C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Scare    │
│ /league/n ┆ 32.410895 ┆ 32.840358 ┆ 29.780194 ┆ … ┆ 28.250111 ┆ 2025-04-0 ┆ 74        ┆ Bin/BTR  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ | Yousef │
│ ayer/17A4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3CB…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.131757 ┆ 32.677573 ┆ 29.732506 ┆ … ┆ 28.259973 ┆ 2025-04-1 ┆ 32        ┆ Ant      │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ ayer/5DBC ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C34…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.450624 ┆ 32.3118   ┆ 30.129517 ┆ … ┆ 29.038376 ┆ 2025-04-1 ┆ 67        ┆ hc |     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆ kraft    │
│ ayer/0CDB ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 30.355508 ┆ 25.364721 ┆ 16.554637 ┆ … ┆ 12.149594 ┆ 2025-03-0 ┆ 120       ┆ Rat Ratt │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆ ington   │
│ ayer/FA73 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F3A…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Using data outside season for non candidates who didn't enter enough

In [7]:
matches_with_ratings = rating_utils.calculate_ratings(
    matches.filter(pl.col('tournament_date') > year_before_season),
    season_start, season_end, sigma_fix=2.0,
)

In [8]:
player_ratings = rating_utils.get_final_ratings(matches_with_ratings)

In [9]:
pl.Config(tbl_rows=20)
candidate_placings = (
    player_ratings
    .filter(pl.col('url').is_in(candidates.select('url').to_series().to_list()))
    .select(pl.exclude('url', 'pi', 'tau', 'exposure'))
)
candidate_placings

shape: (17, 8)
┌────────────┬───────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┐
│ starting_r ┆ rating    ┆ rating_95c ┆ rating_95c ┆ sigma    ┆ tournament ┆ encounter ┆ tag       │
│ ating      ┆ ---       ┆ i_lower    ┆ i_upper    ┆ ---      ┆ _date      ┆ _id       ┆ ---       │
│ ---        ┆ f64       ┆ ---        ┆ ---        ┆ f64      ┆ ---        ┆ ---       ┆ str       │
│ f64        ┆           ┆ f64        ┆ f64        ┆          ┆ str        ┆ i64       ┆           │
╞════════════╪═══════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╡
│ 40.107273  ┆ 40.107273 ┆ 38.322631  ┆ 41.891916  ┆ 0.892321 ┆ 2025-04-19 ┆ 82        ┆ Younger   │
│ 40.046293  ┆ 40.046293 ┆ 38.184759  ┆ 41.907828  ┆ 0.930767 ┆ 2025-03-16 ┆ 335       ┆ $G|MP |   │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Bank      │
│ 37.933219  ┆ 37.822569 ┆ 35.785493  ┆ 39.859645  ┆ 1.018538 ┆ 2025-03-25 ┆ 115       ┆ regEx     │
│ 37.509857  ┆ 37.509857 ┆ 35.765299  ┆ 39.254416  ┆ 0.872279 ┆ 2025-04-19 ┆ 17        ┆ OUG | Ele │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ ctroman   │
│ 37.235979  ┆ 36.816083 ┆ 32.603695  ┆ 41.028471  ┆ 2.106194 ┆ 2025-04-05 ┆ 37        ┆ s6 |      │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ shmeeli   │
│ 36.650848  ┆ 36.650848 ┆ 34.909572  ┆ 38.392125  ┆ 0.870638 ┆ 2025-03-01 ┆ 120       ┆ Rat Ratti │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ ngton     │
│ 36.29606   ┆ 36.564164 ┆ 34.381296  ┆ 38.747032  ┆ 1.091434 ┆ 2025-04-15 ┆ 32        ┆ Ant       │
│ 35.984344  ┆ 35.984344 ┆ 34.163184  ┆ 37.805504  ┆ 0.91058  ┆ 2025-04-14 ┆ 13        ┆ N0va | hc │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ |         │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Coolslice │
│ 35.497192  ┆ 35.140208 ┆ 31.783406  ┆ 38.49701   ┆ 1.678401 ┆ 2025-04-11 ┆ 72        ┆ Greenstac │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ h         │
│ 34.975403  ┆ 34.975403 ┆ 33.006007  ┆ 36.944798  ┆ 0.984698 ┆ 2025-03-16 ┆ 168       ┆ MEAT      │
│ 34.861248  ┆ 34.861248 ┆ 33.001295  ┆ 36.7212    ┆ 0.929976 ┆ 2025-04-19 ┆ 29        ┆ Nage      │
│ 34.695615  ┆ 34.794809 ┆ 32.62325   ┆ 36.966369  ┆ 1.08578  ┆ 2025-04-05 ┆ 42        ┆ Comcast | │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ The       │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ CoveCare  │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Scare     │
│ 34.373154  ┆ 34.318438 ┆ 31.58296   ┆ 37.053916  ┆ 1.367739 ┆ 2025-04-19 ┆ 29        ┆ NEU |     │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ saucymain │
│ 34.226215  ┆ 34.226215 ┆ 32.479852  ┆ 35.972579  ┆ 0.873182 ┆ 2025-04-09 ┆ 16        ┆ Future    │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Shock     │
│ 33.994821  ┆ 33.994821 ┆ 31.942897  ┆ 36.046745  ┆ 1.025962 ┆ 2025-04-01 ┆ 74        ┆ Bin/BTR | │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ Yousef    │
│ 33.687638  ┆ 33.549682 ┆ 31.383697  ┆ 35.715667  ┆ 1.082992 ┆ 2025-04-15 ┆ 67        ┆ hc |      │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ kraft     │
│ 32.559186  ┆ 32.734769 ┆ 28.567645  ┆ 36.901893  ┆ 2.083562 ┆ 2025-04-14 ┆ 43        ┆ MATE |    │
│            ┆           ┆            ┆            ┆          ┆            ┆           ┆ 22K       │
└────────────┴───────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┘

In [10]:
matches_with_difference = (
    matches_with_ratings
    .join(player_ratings.select('url', pl.col('rating').alias('winner_final_rating')), left_on='winner_url', right_on='url')
    .join(player_ratings.select('url', pl.col('rating').alias('loser_final_rating')), left_on='loser_url', right_on='url')
    .with_columns((pl.col('winner_final_rating') - pl.col('loser_final_rating')).alias('final_rating_difference'))
    .select('winner_url', 'winner', 'winner_final_rating', 'loser_url', 'loser', 'loser_final_rating', 'final_rating_difference')
)

# Match Analysis

If some player's rating is higher $\beta$ than another player's, the player may have about a 76% (specifically $\Phi(\frac {1}{\sqrt{2}}))$ chance to beat the other player. The default value of $\beta$ is $\frac{ 25 }{ 6 }$.

## Wins in order of rating difference

In [11]:
def best_wins(matches: pl.DataFrame, player_url: str) -> pl.DataFrame:
    return (
        matches
        .filter(pl.col('winner_url').str.contains(player_url))
        .sort('final_rating_difference')
        .select(pl.exclude(r'^.*url$'))
        .select(pl.exclude(r'^winner.*$'))
        .head(100)
    )

## Losses in order of rating difference

In [12]:
def worst_losses(matches: pl.DataFrame, player_url: str) -> pl.DataFrame:
    return (
        matches
        .filter(pl.col('loser_url').str.contains(player_url))
        .select(pl.exclude(r'^.*url$'))
        .select(pl.exclude(r'^loser.*$'))
        .sort('final_rating_difference')
    )

In [13]:
def display_side_by_side(*args, titles=('',)):
    html_str = ''
    if len(titles) > 0:
        html_str += '<div style="display:flex">'
    for df, title in zip(args, titles + ('',) * (len(args) - len(titles))):
        html_str += '<div style="margin-right:20px">'
        if title:
            html_str += f'<h2>{title}</h2>'
        html_str += df.to_html()
        html_str += '</div>'
    html_str += '</div>'
    display(HTML(html_str))

In [14]:
def display_player_comparison(matches: pl.DataFrame, player1: str, player2: str) -> pl.DataFrame:
    display_side_by_side(
        best_wins(matches, player1).to_pandas(),
        best_wins(matches, player2).to_pandas(),
    )
    display_side_by_side(
        worst_losses(matches, player1).to_pandas(),
        worst_losses(matches, player2).to_pandas(),
    )

In [16]:
pl.Config(tbl_rows=100)
for i in range(0, len(candidate_urls) - 1):
    first_candidate = candidate_placings.slice(i, 1).select('tag').item()
    second_candidate = candidate_placings.slice(i+1, 1).select('tag').item()
    print(f"Comparing {first_candidate} and {second_candidate}")
    display_player_comparison(matches_with_difference, candidate_urls[i], candidate_urls[i+1])

Comparing Younger and $G|MP | Bank

NameError: name 'HTML' is not defined