In [1]:
import os
import re

# This script is used to set the working directory to the root of the project.
cwd = os.getcwd()
project_name = 'braacket-scraper'
project_root = re.split(rf'(?!.*({project_name}))/(.+)$', cwd)[0]
os.chdir(project_root)
project_root

'/home/agiera/ssbm/braacket-scraper'

In [2]:
import polars as pl
import rating_utils
from IPython.display import display, HTML

In [3]:
year_before_season = '2023-11-03'
season_start = '2025-04-20'
season_end = '2025-10-18'

In [4]:
candidates = pl.DataFrame([
    ["/league/nemelee/player/11CA20C1-5FDF-4A64-BC6C-0B5B91497FE7?", "MATE | 22K"],
    ["/league/nemelee/player/5DBCC342-92B6-40C6-AFBF-66933EF41379?", "Ant"],
    ["/league/nemelee/player/E85EE0F4-C335-4A1C-A569-BE69C1675BAA?", "$G|MP | Bank"],
    ["/league/nemelee/player/583438BD-F9A1-413A-8F77-DEF3820143F0?", "N0va | hc | Coolslice"],
    ["/league/nemelee/player/BAB54F38-444F-4ADE-8D79-EC7D232D90E9?", "OUG | Electroman"],
    ["/league/nemelee/player/5CD3DDFC-6380-4395-8DF7-590D498437E2?", "Future Shock"],
    ["/league/nemelee/player/0267F6B4-223B-4D0D-B0AB-3B7084B37AB7?", "Greenstach"],
    ["/league/nemelee/player/EAE5E0CC-99FF-49EB-8424-142348454761?", "Comcast | The CoveCare Scare"],
    ["/league/nemelee/player/3576ECE4-EACF-4E83-995C-F40FB232EADD?", 'Hysteric'],
    ["/league/nemelee/player/0CDB11B1-BCC3-4027-90F2-D74F1A9A5668?", "hc | kraft"],
    ["/league/nemelee/player/0D8C1F36-D79B-4FEF-91DE-5963AC99D13D?", "MEAT"],
    ["/league/nemelee/player/E12030B6-0105-48C8-8D9F-C89581A6F3B9?", 'Motobug'],
    ["/league/nemelee/player/8FF9A4C4-C07C-4DB0-9BAC-9549C3DEB401?", 'oz'],
    ["/league/nemelee/player/1D8B9E33-86AE-45FB-89E9-0CB158C24FD3?", "regEx"],
    ["/league/nemelee/player/2407F41F-64A0-43AF-85F1-96F6985E57EE?", "hc | saucymain"],
    ["/league/nemelee/player/DF3CE0B4-0BA0-493F-99F3-879CD12469FD?", 'Sweat'],
    ["/league/nemelee/player/62EEC119-0B50-4FC8-BE56-F566A076EB0A?", "Gambit"],
], orient="row", schema=["url", "tag"])
candidate_urls = candidates.select('url').to_series().to_list()


# Load Data

In [5]:
matches = pl.read_csv("data/matches.csv")
season_matches = (
    matches
    .filter(pl.col('tournament_date') >= season_start)
    .filter(pl.col('tournament_date') <= season_end)
)

## Using just season data

In [6]:
season_matches_with_ratings = rating_utils.calculate_ratings(matches, season_start, season_end)
season_player_ratings = rating_utils.get_final_ratings(season_matches_with_ratings)
pl.Config(tbl_rows=20)
season_player_ratings.filter(pl.col('url').str.contains_any(candidate_urls))

/home/agiera/ssbm/braacket-scraper/rating_utils.py:147: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(

shape: (17, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ starting_ ┆ rating    ┆ rating_95 ┆ … ┆ exposure  ┆ tournamen ┆ encounter ┆ tag      │
│ ---       ┆ rating    ┆ ---       ┆ ci_lower  ┆   ┆ ---       ┆ t_date    ┆ _id       ┆ ---      │
│ str       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ str      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆           ┆ str       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ /league/n ┆ 35.990487 ┆ 36.230861 ┆ 32.545465 ┆ … ┆ 30.702767 ┆ 2025-10-1 ┆ 87        ┆ OUG |    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ Electrom │
│ ayer/BAB5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ an       │
│ 4F3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 39.668469 ┆ 35.475246 ┆ 28.592827 ┆ … ┆ 25.151617 ┆ 2025-10-1 ┆ 70        ┆ regEx    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆          │
│ ayer/1D8B ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9E3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 35.002718 ┆ 35.282463 ┆ 32.967783 ┆ … ┆ 31.810443 ┆ 2025-10-1 ┆ 51        ┆ N0va |   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ hc | Coo │
│ ayer/5834 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ lslice   │
│ 38B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.158758 ┆ 34.438089 ┆ 29.575058 ┆ … ┆ 27.143543 ┆ 2025-10-1 ┆ 83        ┆ hc | sau │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ cymain   │
│ ayer/2407 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F41…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 34.069209 ┆ 34.087749 ┆ 32.250819 ┆ … ┆ 31.332354 ┆ 2025-10-1 ┆ 89        ┆ Comcast  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ | The    │
│ ayer/EAE5 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ CoveCare │
│ E0C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Scare    │
│ /league/n ┆ 33.551028 ┆ 33.731655 ┆ 31.090296 ┆ … ┆ 29.769617 ┆ 2025-10-0 ┆ 126       ┆ MEAT     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ ayer/0D8C ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1F3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.722688 ┆ 33.564796 ┆ 31.796368 ┆ … ┆ 30.912154 ┆ 2025-10-1 ┆ 86        ┆ Future   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ Shock    │
│ ayer/5CD3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DDF…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 33.63362  ┆ 33.503327 ┆ 31.506919 ┆ … ┆ 30.508715 ┆ 2025-10-0 ┆ 70        ┆ Ant      │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ ayer/5DBC ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C34…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.769562 ┆ 32.553059 ┆ 29.957226 ┆ … ┆ 28.65931  ┆ 2025-10-0 ┆ 71        ┆ Hysteric │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ ayer/3576 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ECE…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.671692 ┆ 32.470469 ┆ 29.806872 ┆ … ┆ 28.475074 ┆ 2025-10-0 ┆ 72        ┆ hc |     │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 7         ┆           ┆ kraft    │
│ ayer/0CDB ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.878711 ┆ 32.417556 ┆ 29.386724 ┆ … ┆ 27.871308 ┆ 2025-09-0 ┆ 66        ┆ Sweat    │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ ayer/DF3C ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ E0B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 32.98538  ┆ 32.376478 ┆ 28.300505 ┆ … ┆ 26.262518 ┆ 2025-09-2 ┆ 18        ┆ MATE |   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ 22K      │
│ ayer/11CA ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 29.978154 ┆ 30.887764 ┆ 26.858215 ┆ … ┆ 24.843441 ┆ 2025-10-1 ┆ 52        ┆ Greensta │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ ch       │
│ ayer/0267 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ F6B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 30.983288 ┆ 30.79985  ┆ 28.19199  ┆ … ┆ 26.88806  ┆ 2025-10-1 ┆ 37        ┆ Motobug  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ ayer/E120 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 30B…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 30.353355 ┆ 30.272805 ┆ 28.472863 ┆ … ┆ 27.572892 ┆ 2025-10-1 ┆ 88        ┆ oz       │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆          │
│ ayer/8FF9 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A4C…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 29.533949 ┆ 30.177021 ┆ 24.142769 ┆ … ┆ 21.125644 ┆ 2025-10-1 ┆ 85        ┆ $G|MP |  │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆ Bank     │
│ ayer/E85E ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ E0F…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ /league/n ┆ 25.790451 ┆ 29.543574 ┆ 18.443751 ┆ … ┆ 12.89384  ┆ 2025-10-1 ┆ 90        ┆ Gambit   │
│ emelee/pl ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆          │
│ ayer/62EE ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C11…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Using data outside season for non candidates who didn't enter enough

In [7]:
matches_with_ratings = rating_utils.calculate_ratings(
    matches.filter(pl.col('tournament_date') > year_before_season),
    season_start, season_end, sigma_fix=2.0,
)

/home/agiera/ssbm/braacket-scraper/rating_utils.py:147: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(
/home/agiera/ssbm/braacket-scraper/rating_utils.py:147: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(
/home/agiera/ssbm/braacket-scraper/rating_utils.py:147: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  .with_columns(

In [8]:
player_ratings = rating_utils.get_final_ratings(matches_with_ratings)

In [9]:
pl.Config(tbl_rows=20)
candidate_placings = (
    player_ratings
    .filter(pl.col('url').str.contains_any(candidate_urls))
    .select(pl.exclude('starting_rating', 'url', 'pi', 'tau', 'exposure', 'encounter_id'))
)
candidate_placings

shape: (17, 6)
┌───────────┬───────────────────┬──────────────────┬──────────┬─────────────────┬──────────────────┐
│ rating    ┆ rating_95ci_lower ┆ rating_95ci_uppe ┆ sigma    ┆ tournament_date ┆ tag              │
│ ---       ┆ ---               ┆ r                ┆ ---      ┆ ---             ┆ ---              │
│ f64       ┆ f64               ┆ ---              ┆ f64      ┆ str             ┆ str              │
│           ┆                   ┆ f64              ┆          ┆                 ┆                  │
╞═══════════╪═══════════════════╪══════════════════╪══════════╪═════════════════╪══════════════════╡
│ 39.002443 ┆ 35.444615         ┆ 42.560271        ┆ 1.778914 ┆ 2025-10-18      ┆ OUG | Electroman │
│ 38.734664 ┆ 36.976077         ┆ 40.49325         ┆ 0.879293 ┆ 2025-10-18      ┆ $G|MP | Bank     │
│ 38.045804 ┆ 36.327417         ┆ 39.764191        ┆ 0.859193 ┆ 2025-10-14      ┆ regEx            │
│ 36.715869 ┆ 34.369503         ┆ 39.062235        ┆ 1.173183 ┆ 2025-10-18      ┆ N0va | hc |      │
│           ┆                   ┆                  ┆          ┆                 ┆ Coolslice        │
│ 36.433685 ┆ 34.732805         ┆ 38.134565        ┆ 0.85044  ┆ 2025-10-18      ┆ Greenstach       │
│ 35.445605 ┆ 33.68859          ┆ 37.202619        ┆ 0.878507 ┆ 2025-10-18      ┆ hc | saucymain   │
│ 35.246728 ┆ 32.550986         ┆ 37.94247         ┆ 1.347871 ┆ 2025-10-05      ┆ MEAT             │
│ 34.839386 ┆ 33.017637         ┆ 36.661136        ┆ 0.910875 ┆ 2025-10-18      ┆ Comcast | The    │
│           ┆                   ┆                  ┆          ┆                 ┆ CoveCare Scare   │
│ 34.366552 ┆ 32.350573         ┆ 36.38253         ┆ 1.007989 ┆ 2025-10-07      ┆ Ant              │
│ 34.159223 ┆ 32.381939         ┆ 35.936507        ┆ 0.888642 ┆ 2025-10-18      ┆ Future Shock     │
│ 33.533825 ┆ 30.933921         ┆ 36.133728        ┆ 1.299952 ┆ 2025-10-07      ┆ Hysteric         │
│ 33.49859  ┆ 30.406861         ┆ 36.590319        ┆ 1.545865 ┆ 2025-09-02      ┆ Sweat            │
│ 33.368574 ┆ 30.697848         ┆ 36.039301        ┆ 1.335363 ┆ 2025-10-07      ┆ hc | kraft       │
│ 31.980652 ┆ 29.329333         ┆ 34.631971        ┆ 1.32566  ┆ 2025-10-15      ┆ Motobug          │
│ 31.839937 ┆ 30.067847         ┆ 33.612028        ┆ 0.886045 ┆ 2025-09-28      ┆ MATE | 22K       │
│ 31.725166 ┆ 29.952529         ┆ 33.497803        ┆ 0.886318 ┆ 2025-10-18      ┆ Gambit           │
│ 31.003236 ┆ 29.182892         ┆ 32.82358         ┆ 0.910172 ┆ 2025-10-18      ┆ oz               │
└───────────┴───────────────────┴──────────────────┴──────────┴─────────────────┴──────────────────┘

In [10]:
matches_with_difference = (
    matches_with_ratings
    .join(player_ratings.select('url', pl.col('rating').alias('winner_final_rating')), left_on='winner_url', right_on='url')
    .join(player_ratings.select('url', pl.col('rating').alias('loser_final_rating')), left_on='loser_url', right_on='url')
    .with_columns((pl.col('winner_final_rating') - pl.col('loser_final_rating')).alias('final_rating_difference'))
    .select('winner_url', 'winner', 'winner_final_rating', 'loser_url', 'loser', 'loser_final_rating', 'final_rating_difference')
)

# Match Analysis

If some player's rating is higher $\beta$ than another player's, the player may have about a 76% (specifically $\Phi(\frac {1}{\sqrt{2}}))$ chance to beat the other player. The default value of $\beta$ is $\frac{ 25 }{ 6 }$.

## Wins in order of rating difference

In [11]:
def best_wins(matches: pl.DataFrame, player_url: str) -> pl.DataFrame:
    return (
        matches
        .filter(pl.col('winner_url').str.contains(player_url))
        .sort('final_rating_difference')
        .select(pl.exclude(r'^.*url$'))
        .select(pl.exclude(r'^winner.*$'))
        .head(100)
    )

## Losses in order of rating difference

In [12]:
def worst_losses(matches: pl.DataFrame, player_url: str) -> pl.DataFrame:
    return (
        matches
        .filter(pl.col('loser_url').str.contains(player_url))
        .select(pl.exclude(r'^.*url$'))
        .select(pl.exclude(r'^loser.*$'))
        .sort('final_rating_difference')
    )

In [13]:
def display_side_by_side(*args, titles=('',)):
    html_str = ''
    if len(titles) > 0:
        html_str += '<div style="display:flex">'
    for df, title in zip(args, titles + ('',) * (len(args) - len(titles))):
        html_str += '<div style="margin-right:20px">'
        if title:
            html_str += f'<h2>{title}</h2>'
        html_str += df.to_html()
        html_str += '</div>'
    html_str += '</div>'
    display(HTML(html_str))

In [14]:
def display_player_comparison(matches: pl.DataFrame, player1: str, player2: str) -> pl.DataFrame:
    display_side_by_side(
        best_wins(matches, player1).to_pandas(),
        best_wins(matches, player2).to_pandas(),
    )
    display_side_by_side(
        worst_losses(matches, player1).to_pandas(),
        worst_losses(matches, player2).to_pandas(),
    )

In [15]:
pl.Config(tbl_rows=100)
for i in range(0, len(candidate_urls) - 1):
    first_candidate = candidate_placings.slice(i, 1).select('tag').item()
    second_candidate = candidate_placings.slice(i+1, 1).select('tag').item()
    print(f"Comparing {first_candidate} and {second_candidate}")
    display_player_comparison(matches_with_difference, candidate_urls[i], candidate_urls[i+1])

Comparing OUG | Electroman and $G|MP | Bank

Comparing $G|MP | Bank and regEx

Comparing regEx and N0va | hc | Coolslice

Comparing N0va | hc | Coolslice and Greenstach

Comparing Greenstach and hc | saucymain

Comparing hc | saucymain and MEAT

Comparing MEAT and Comcast | The CoveCare Scare

Comparing Comcast | The CoveCare Scare and Ant

Comparing Ant and Future Shock

Comparing Future Shock and Hysteric

Comparing Hysteric and Sweat

Comparing Sweat and hc | kraft

Comparing hc | kraft and Motobug

Comparing Motobug and MATE | 22K

Comparing MATE | 22K and Gambit

Comparing Gambit and oz